// <auto-generated />
namespace MCDataBookLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MyMigration14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MyMigration14));
        
        string IMigrationMetadata.Id
        {
            get { return "201711231756169_MyMigration14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
